#ifndef cEEpromInitH
#define cEEpromInitH
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
//---------------------------------------------------------------------------
class TEEpromInit : public TForm
{
__published:	// IDE-managed Components
	TLabel *Label1;
	TLabel *BuBeir;
	TLabel *BuKilep;
	TLabel *BuOlvas;
	TLabel *Uzen;
	TGroupBox *GroupKartyaolvaso1;
	TGroupBox *GroupKutfok;
	TCheckBox *Kut1;
	TCheckBox *Kut2;
	TCheckBox *Kut3;
	TCheckBox *Kut4;
	TCheckBox *Kut5;
	TCheckBox *Kut6;
	TCheckBox *Kut7;
	TCheckBox *Kut8;
	TGroupBox *GroupStatusz;
	TCheckBox *StaLiter;
	TCheckBox *StaMenlev;
	TCheckBox *StaCard;
	TCheckBox *StaUzem;
	TCheckBox *StaKm;
	TGroupBox *GroupKontraszt;
	TEdit *Kontraszt;
	TCheckBox *StaKmNov;
	TEdit *KontKomp;
	TLabel *LabKontraszt;
	TLabel *LabKontKomopenz;
	TLabel *LabHoSzorzo;
	TEdit *Ho1Szor;
	TLabel *LabHoOffset;
	TEdit *Ho1Offs;
	TLabel *Label8;
	TGroupBox *GroupNyomtatas;
	TLabel *LabPeldanyszam;
	TEdit *TankDb;
	TLabel *LabVezerloSzam;
	TEdit *VezNum;
	TEdit *BeBenzin1;
	TEdit *BeBenzin2;
	TEdit *BeBenzin3;
	TEdit *BeBenzin4;
	TEdit *BeBenzin5;
	TEdit *BeBenzin6;
	TEdit *BeBenzin7;
	TEdit *BeBenzin8;
	TLabel *LabOlaj;
	TLabel *LabBenzin;
	TCheckBox *Kut9;
	TCheckBox *Kut10;
	TCheckBox *Kut11;
	TCheckBox *Kut12;
	TCheckBox *Kut13;
	TCheckBox *Kut14;
	TCheckBox *Kut15;
	TEdit *BeBenzin9;
	TEdit *BeBenzin10;
	TEdit *BeBenzin12;
	TEdit *BeBenzin13;
	TEdit *BeBenzin14;
	TEdit *BeBenzin15;
	TEdit *BeBenzin11;
	TGroupBox *GroupSzint1;
	TCheckBox *S1_1;
	TCheckBox *S1_2;
	TCheckBox *S1_3;
	TCheckBox *S1_4;
	TCheckBox *S1_5;
	TCheckBox *S1_6;
	TCheckBox *S1_7;
	TCheckBox *S1_8;
	TCheckBox *S1_9;
	TCheckBox *S1_10;
	TCheckBox *S1_11;
	TCheckBox *S1_12;
	TCheckBox *S1_13;
	TCheckBox *S1_14;
	TCheckBox *S1_15;
	TEdit *BeSzintNum1;
	TGroupBox *GroupSzint2;
	TEdit *BeSzintNum2;
	TCheckBox *S2_1;
	TCheckBox *S2_2;
	TCheckBox *S2_3;
	TCheckBox *S2_4;
	TCheckBox *S2_5;
	TCheckBox *S2_6;
	TCheckBox *S2_7;
	TCheckBox *S2_8;
	TCheckBox *S2_9;
	TCheckBox *S2_10;
	TCheckBox *S2_11;
	TCheckBox *S2_12;
	TCheckBox *S2_13;
	TCheckBox *S2_14;
	TCheckBox *S2_15;
	TGroupBox *GroupIdozitesek;
	TLabel *LabMnuVissza;
	TEdit *BeMnuTimeout;
	TLabel *LabMnuVissza2;
	TLabel *LabMnuUtanvil;
	TEdit *BeMnuUtoTime;
	TLabel *LabMnuUtanvil2;
	TRadioButton *CardRead1;
	TRadioButton *CardRead2;
	TRadioButton *CardRead3;
	TRadioButton *CardRead4;
	TGroupBox *GroupGyurus;
	TLabel *LabPisztoly1;
	TLabel *LabPisztoly2;
	TLabel *LabPisztoly3;
	TEdit *Gyurus1;
	TEdit *Gyurus2;
	TEdit *Gyurus3;
	TLabel *LabPistNincs;
	TLabel *LabOistNum;
	TRadioButton *CardRead5;
	TCheckBox *StaEkod;
	TRadioButton *CardRead6;
	TCheckBox *StaKmKetszer;
	TCheckBox *StaAutoStr;
	TRadioButton *CardRead7;
	TLabel *LabVirtualis;
	TComboBox *K4Nyelv;
	TLabel *LabNyelv;
	TGroupBox *GroupKartyaolvaso2;
	TRadioButton *CardRead20;
	TRadioButton *CardRead21;
	TRadioButton *CardRead22;
	TEdit *CrossPointCim;
     TGroupBox *GroupSzint3;
     TCheckBox *S3_1;
     TCheckBox *S3_2;
     TCheckBox *S3_3;
     TCheckBox *S3_4;
     TCheckBox *S3_5;
     TCheckBox *S3_6;
     TCheckBox *S3_7;
     TCheckBox *S3_8;
     TCheckBox *S3_9;
     TCheckBox *S3_10;
     TCheckBox *S3_11;
     TCheckBox *S3_12;
     TCheckBox *S3_13;
     TCheckBox *S3_14;
     TCheckBox *S3_15;
     TGroupBox *GroupSzint4;
     TCheckBox *S4_1;
     TCheckBox *S4_2;
     TCheckBox *S4_3;
     TCheckBox *S4_4;
     TCheckBox *S4_5;
     TCheckBox *S4_6;
     TCheckBox *S4_7;
     TCheckBox *S4_8;
     TCheckBox *S4_9;
     TCheckBox *S4_10;
     TCheckBox *S4_11;
     TCheckBox *S4_12;
     TCheckBox *S4_13;
     TCheckBox *S4_14;
     TCheckBox *S4_15;
	TCheckBox *StaMaxStop;
	void __fastcall BuBeirClick(TObject *Sender);
	void __fastcall BuKilepClick(TObject *Sender);
	void __fastcall BuOlvasClick(TObject *Sender);
	void __fastcall FormKeyPress(TObject *Sender, char &Key);
	void __fastcall StaKmClick(TObject *Sender);
	void __fastcall FormActivate(TObject *Sender);
private:	// User declarations
	Byte		epr[130];
	Byte		Kiolv, Beir;
	void __fastcall TEEpromInit::Kiolv50ms(void);
	void __fastcall TEEpromInit::Beir50ms(void);
public:		// User declarations
	void __fastcall TEEpromInit::Timer50ms(void);
	__fastcall TEEpromInit(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TEEpromInit *EEpromInit;
//---------------------------------------------------------------------------
#endif
